### ISSUE TITLE
Multiple Clients Connecting to Host

### ISSUE THREAD

**Issue by JackOBrien** [JackOBrien/Concurrent-Editor#8]
The server/host should be able to handle one or more clients.

**Comment by maknapp** [comment]
So apparently this already works. I don't know how you guys have been testing, I've been testing multiple clients by having three projects open on one computer, making one project a server and the other two as clients. When typing into the server editor, every project crashes. However, it does not crash as long as the two clients are not on the same machine. I think that opening multiple projects on one machine is still only running the plugin once and some things are overwritten or shared between the project windows.

The only part that does not work then is having the server resend edits it receives to everyone else except the original sender. This can only be done when the edits have IDs though.

**Comment by JackOBrien** [comment]
Interesting, I didn't think to try it on several machines. Should we close the branch then?

**Comment by maknapp** [comment]
Branch deleted.
